### PR TITLE
Add copy to clipboard functionality

### LINKED ISSUE #4: Copy-to-clipboard button
It's nice to have such button, especially on mobile platforms.

### PR DESCRIPTION
**Pull request by ghost**
closes #4

### CODE REVIEW

**Comment by zelark** [comment]
@korlando7 thanks for the PR. I glad to see you want to help. However, there are few remarks.
1) It doesn't work properly in Chrome (I used the latest version). I click to the button, but nothing happens. In Firefox it works perfect.
2) After copying the selection remains.

You can use https://clipboardjs.com/ as an example of how I'd like it works. Tooltip is not needed for now, but I expect the same mechanics.

**Comment by ghost** [comment]
@zelark thanks for the constructive feedback, I will check out your requests and address them soon.

**Comment by ghost** [comment]
@zelark let me know if this is working for you now. I tested in both Chrome and Firefox and was successfully able to add the code to the clipboard.

**Review by zelark — COMMENTED** [review]
Tasted in Firefox and Chrome. Works. I'm going to publish the code and do some more tests before I accept it.

**Comment by ghost** [comment]
@zelark sounds good.

Thanks for cleaning up the code and removing the thread operator, I should have done that earlier. Also, I didn't see a linter in the project.clj, let me know if I missed it. I usually use [cljfmt](https://github.com/weavejester/cljfmt)

**Comment by zelark** [comment]
I use clj-kondo as a linter. It doesn't require any config in `project.clj`.

**Comment by zelark** [comment]
Just deployed https://zelark.github.io/nano-id-cc/.

**Comment by ghost** [comment]
clj-kondo looks awesome, thanks for sharing

**Review by zelark — APPROVED** [review]

**Pull request merged**
